<a href="https://colab.research.google.com/github/chavacodezen/Maestria-IA/blob/main/Practica4_268838.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*   Nombre: Bryan Fernando Chavarria Martinez
*   Matricula: 268838

Actividad:
*   Manipulación de matrices.
*   Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:
1.   Suma ambas matrices.
2.   Resta la segunda matriz de la primera.
3.   Multiplica la primera matriz por 2.
4.   Realiza una multiplicación matricial entre las dos matrices.

In [1]:
import numpy as np

# Matrices 3x3 (valores aleatorios entre 1 y 10)
matriz1 = np.random.randint(1, 11, size=(3, 3))
matriz2 = np.random.randint(1, 11, size=(3, 3))

print("Matriz 1:")
print(matriz1)

print("\nMatriz 2:")
print(matriz2)

Matriz 1:
[[ 1  4  7]
 [ 5  9 10]
 [ 9  1  5]]

Matriz 2:
[[ 1 10  9]
 [ 8  3  2]
 [ 5  7  9]]


In [2]:
# Suma de ambas matrices (elemento a elemento)
suma = matriz1 + matriz2
print("\nSuma de matrices:")
print(suma)


Suma de matrices:
[[ 2 14 16]
 [13 12 12]
 [14  8 14]]


In [3]:
# Resta de la segunda matriz a la primera (elemento a elemento)
resta = matriz1 - matriz2
print("\nResta de matrices:")
print(resta)


Resta de matrices:
[[ 0 -6 -2]
 [-3  6  8]
 [ 4 -6 -4]]


In [4]:
# Multiplicar la primera matriz por 2 (escalar)
multiplicacion_escalar = matriz1 * 2
print("\nMatriz 1 multiplicada por 2:")
print(multiplicacion_escalar)


Matriz 1 multiplicada por 2:
[[ 2  8 14]
 [10 18 20]
 [18  2 10]]


In [5]:
# Multiplicación matricial (producto punto)
multiplicacion_matricial = np.dot(matriz1, matriz2)

print("\nMultiplicación matricial:")
print(multiplicacion_matricial)


Multiplicación matricial:
[[ 68  71  80]
 [127 147 153]
 [ 42 128 128]]
